# Generated by Django 5.2.7 on 2025-10-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_device_room_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='state',
        ),
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False, verbose_name='on'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='enable_thermal',
            field=models.BooleanField(default=False, verbose_name='Enable thermal rules'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='enable_time',
            field=models.BooleanField(default=False, verbose_name='Enable time rules'),
        ),
    ]
