# Generated by Django 5.2.7 on 2025-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_devicetype_state_device_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_monitor_state',
            field=models.BooleanField(default=False, verbose_name='monitor state'),
        ),
    ]
