# Generated by Django 5.2.7 on 2025-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_is_monitor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_on',
            field=models.BooleanField(default=False, verbose_name='power_on'),
        ),
    ]
