# Generated by Django 5.2.7 on 2025-11-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_power_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
