# Generated by Django 5.2.7 on 2025-11-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_devicetype_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='updated',
        ),
        migrations.AddField(
            model_name='device',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
