# Generated by Django 5.2.7 on 2025-11-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_remove_devicetype_updated_device_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
