# Generated by Django 5.2.7 on 2025-10-25 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0004_remove_devicetype_state_device_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_type', models.CharField(choices=[('thermal', 'Thermal Logic'), ('time', 'Time Logic')], max_length=20)),
                ('mac_address', models.CharField(max_length=11)),
                ('active', models.BooleanField(default=True)),
                ('numeric_max', models.FloatField()),
                ('numeric_min', models.FloatField()),
                ('time_max', models.TimeField()),
                ('time_min', models.TimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
