# Generated by Django 5.2.7 on 2025-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logiccontroller',
            name='name',
            field=models.CharField(default='Rule', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='numeric_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='numeric_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_max',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_min',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
