# Generated by Django 5.2.7 on 2025-10-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiccontroller',
            name='numeric_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='numeric_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_max',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_min',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
