# Generated by Django 5.2.7 on 2025-11-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0002_alter_logiccontroller_numeric_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logiccontroller',
            name='name',
            field=models.CharField(default='Rule', max_length=200, verbose_name='name'),
        ),
    ]
