# Generated by Django 5.2.7 on 2025-11-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0002_logiccontroller_name_and_more'),
        ('logic_module', '0003_logiccontroller_name'),
    ]

    operations = [
    ]
