# Generated by Django 5.2.7 on 2025-11-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0004_merge_20251105_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logiccontroller',
            name='logic_type',
        ),
        migrations.AddField(
            model_name='logiccontroller',
            name='numeric_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
