# Generated by Django 5.2.7 on 2025-11-11 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0005_remove_logiccontroller_logic_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiccontroller',
            name='numeric_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='numeric_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_max',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_min',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
