# Generated by Django 5.2.7 on 2025-11-18 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0006_alter_logiccontroller_numeric_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_max',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='time_min',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
