# Generated by Django 5.2.7 on 2025-11-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic_module', '0007_alter_logiccontroller_time_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiccontroller',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='logiccontroller',
            name='numeric_value',
            field=models.FloatField(default=0),
        ),
    ]
