# Generated by Django 5.2.7 on 2025-10-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
