# Generated by Django 5.2.7 on 2025-10-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_delete_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeUser',
        ),
    ]
