# Generated by Django 5.2.7 on 2025-11-11 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsDeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(verbose_name='item_id')),
                ('device_name', models.CharField(max_length=200, verbose_name='device_name')),
                ('device_kind', models.CharField(max_length=200, verbose_name='device_kind')),
                ('timestamp', models.DateTimeField(default=1762874742.7393105, verbose_name='timestamp')),
                ('device_on', models.BooleanField(verbose_name='device_on')),
                ('metric', models.CharField(blank=True, max_length=200, null=True, verbose_name='metric')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='StatsUserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=1762874742.7393105, verbose_name='timestamp')),
                ('user_action', models.CharField(max_length=200, verbose_name='user_action')),
                ('item_id', models.IntegerField(blank=True, null=True, verbose_name='item_id')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='item_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
