# Generated by Django 5.2.7 on 2025-11-11 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdevicestate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 17, 23, 32, 718148), verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='statsuseraction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 17, 23, 32, 718148), verbose_name='timestamp'),
        ),
    ]
