# Generated by Django 5.2.7 on 2025-11-11 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_statsdevicestate_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsuseraction',
            name='item_kind',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='item_kind'),
        ),
        migrations.AlterField(
            model_name='statsdevicestate',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='statsuseraction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp'),
        ),
    ]
