# Generated by Django 5.2.7 on 2025-11-11 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_statsdevicestate_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdevicestate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 21, 35, 13, 20738), verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='statsuseraction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 21, 35, 13, 19740), verbose_name='timestamp'),
        ),
    ]
