# Generated by Django 5.2.7 on 2025-11-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_statsdevicestate_timestamp_and_more'),
        ('stats', '0003_statsuseraction_item_kind_and_more'),
    ]

    operations = [
    ]
