# Generated by Django 5.2.7 on 2025-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_statsdevicestate_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsdevicestate',
            name='device_id',
            field=models.IntegerField(verbose_name='device_id'),
        ),
    ]
