# Generated by Django 5.2.7 on 2025-11-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_statsdevicestate_device_id'),
        ('stats', '0006_statsdevicestate_description_and_more'),
    ]

    operations = [
    ]
